### ISSUE TITLE
[BUG] Game incorrectly identifies winner

### ISSUE THREAD

**Issue by b0x207** [LGgameLAB/CL-Tic-Tac-Toe#1]
While playing as X, the following finishing state is reached:

![image](https://user-images.githubusercontent.com/81256789/230618769-1c735783-c586-45af-9229-123b667276c0.png)

Here, O is the winner. However, the game reports the player as having won despite the player being X.

**Comment by LGgameLAB** [comment]
Yep just fixed thank you :)
